name: Clean Up Old Minor Versions

on:
  workflow_run:
    workflows: [ "Test Action" ]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Get the current release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Parse major version
        run: |
          MAJOR_VERSION=$(echo "${RELEASE_VERSION}" | cut -d '.' -f 1)
          echo "MAJOR_VERSION=${MAJOR_VERSION}" >> $GITHUB_ENV

      - name: Get list of tags
        run: |
          # Fetch all tags and filter out the ones matching the last major version
          TAGS=$(gh api repos/${{ github.repository }}/tags | jq -r '.[].name' | grep "^${MAJOR_VERSION}.")
          echo "Tags found: $TAGS"

          # Get the latest minor version tag
          LATEST_MINOR=$(echo "$TAGS" | sort -V | tail -1)
          echo "LATEST_MINOR=${LATEST_MINOR}" >> $GITHUB_ENV

      - name: Delete old minor versions except the last
        if: startsWith(env.RELEASE_VERSION, 'v')
        run: |
          for TAG in $TAGS; do
            if [ "$TAG" != "$LATEST_MINOR" ]; then
              echo "Deleting old tag: $TAG"
              gh api repos/${{ github.repository }}/git/refs/tags/$TAG -X DELETE
            fi
          done
