name: Clean Up Old Minor Versions

on:
  workflow_run:
    workflows: ["Test Action"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          # Authenticate GitHub CLI using the token directly without environment variable conflicts
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Get the latest release tag
        id: get_latest
        run: |
          # Fetch all tags from the remote to ensure the latest tags are available
          git fetch --tags
          
          # Get the latest tag using git describe
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          # Output the latest tag to the logs
          echo "Latest tag: $latest_tag"
          
          # Save the latest tag as an environment variable for use in subsequent steps
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Get the current release version
        run: |
          # Extract the release version from the ref, expected format 'refs/tags/vX.Y.Z'
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
            echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          else
            echo "This action is triggered from a non-tag event: ${GITHUB_REF}"
            exit 1
          fi

      - name: Parse major version
        run: |
          # Extract major version only if the version format is correct
          if [[ "${RELEASE_VERSION}" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
            MAJOR_VERSION=$(echo "${RELEASE_VERSION}" | cut -d '.' -f 1)
            echo "MAJOR_VERSION=${MAJOR_VERSION}" >> $GITHUB_ENV
          else
            echo "Invalid release version format: ${RELEASE_VERSION}"
            exit 1
          fi

      - name: Get list of tags
        run: |
          # Fetch all tags and filter out the ones matching the last major version
          TAGS=$(gh api repos/${{ github.repository }}/tags | jq -r '.[].name' | grep "^${MAJOR_VERSION}.")
          if [ -z "$TAGS" ]; then
            echo "No matching tags found for major version: ${MAJOR_VERSION}"
            exit 1
          fi
          echo "Tags found: $TAGS"

          # Get the latest minor version tag
          LATEST_MINOR=$(echo "$TAGS" | sort -V | tail -1)
          echo "LATEST_MINOR=${LATEST_MINOR}" >> $GITHUB_ENV

      - name: Delete old minor versions except the last
        if: startsWith(env.RELEASE_VERSION, 'v')
        run: |
          for TAG in $TAGS; do
            if [ "$TAG" != "$LATEST_MINOR" ]; then
              echo "Deleting old tag: $TAG"
              gh api repos/${{ github.repository }}/git/refs/tags/$TAG -X DELETE
            fi
          done

      - name: Get list of releases
        run: |
          # Fetch all releases and filter based on the last major version
          RELEASES=$(gh api repos/${{ github.repository }}/releases | jq -r '.[] | select(.tag_name | startswith(env.MAJOR_VERSION)) | .tag_name')
          if [ -z "$RELEASES" ]; then
            echo "No matching releases found for major version: ${MAJOR_VERSION}"
            exit 1
          fi
          echo "Releases found: $RELEASES"

      - name: Delete old releases except the last
        if: startsWith(env.RELEASE_VERSION, 'v')
        run: |
          for RELEASE in $RELEASES; do
            if [ "$RELEASE" != "$LATEST_MINOR" ]; then
              echo "Deleting old release: $RELEASE"
              # Get the release ID and delete it
              RELEASE_ID=$(gh api repos/${{ github.repository }}/releases | jq -r ".[] | select(.tag_name == \"$RELEASE\") | .id")
              gh api repos/${{ github.repository }}/releases/$RELEASE_ID -X DELETE
            fi
          done
