name: Increment Release Version

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the latest release tag
        id: get_latest
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment patch version
        id: increment
        run: |
          version=${tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"
          echo "New version: $new_version"
          echo "new_tag=$new_version" >> $GITHUB_ENV

      - name: Set Git user identity based on repository owner
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Print current README.md content before replacement
        run: |
          grep 'uses: datenwissenschaften/manage-todos-action@' README.md || echo "Pattern not found"

      - name: Update version number in README.md
        run: |
          version=${{ env.new_tag }}
          version_number=${version#v}
          sed -i "s|uses: datenwissenschaften/manage-todos-action@v[0-9.]*|uses: datenwissenschaften/manage-todos-action@v$version_number|" README.md
          
          # Print the updated README.md to verify the changes
          grep 'uses: datenwissenschaften/manage-todos-action@' README.md || echo "Replacement failed"

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update README.md with version $version_number" || echo "Nothing to commit"
          git push origin main --force

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.new_tag }}
          name: ${{ env.new_tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
