name: Delete Commits After Release

on:
  release:
    types: [published]  # Trigger when a new release is published

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  reset-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure access to tags and commits

      - name: Get the latest release tag
        id: get_latest
        run: |
          # Get the latest release tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Reset branch to latest release tag
        run: |
          # Reset to the latest release tag
          git reset --hard ${{ env.tag }}

          # Force push to rewrite the branch history
          git push origin HEAD --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
